/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Ángel
 */
public class menu_cliente extends javax.swing.JFrame {

    /**
     * Creates new form menu_cliente
     */
    public menu_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cerrar_sesion_cliente = new javax.swing.JButton();
        btn_ver_productos_c = new javax.swing.JButton();
        btn_ver_carrito_c = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cerrar_sesion_cliente.setText("Regresar");
        btn_cerrar_sesion_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesion_clienteActionPerformed(evt);
            }
        });

        btn_ver_productos_c.setText("Ver productos");
        btn_ver_productos_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_productos_cActionPerformed(evt);
            }
        });

        btn_ver_carrito_c.setText("Ver carrito");
        btn_ver_carrito_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_carrito_cActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_cerrar_sesion_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 327, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_ver_productos_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ver_carrito_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_cerrar_sesion_cliente)
                .addGap(66, 66, 66)
                .addComponent(btn_ver_productos_c)
                .addGap(26, 26, 26)
                .addComponent(btn_ver_carrito_c)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrar_sesion_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesion_clienteActionPerformed
        Object[] opciones = {"Sí", "No"};
    
    int respuesta = JOptionPane.showOptionDialog(
        this, 
        "¿Quieres cerrar sesión?", 
        "Confirmar cierre de sesión", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        opciones, 
        opciones[1]
    );
    
    if (respuesta == JOptionPane.YES_OPTION) {
        
        this.dispose();
        inicio_clientes objinicio_clientes = new inicio_clientes();
        objinicio_clientes.setVisible(true);
        objinicio_clientes.setLocationRelativeTo(null);
      
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cerrar_sesion_clienteActionPerformed

    private void btn_ver_productos_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_productos_cActionPerformed
       this.dispose();
        Ventas_cliente objventa_clientes = new Ventas_cliente();
        objventa_clientes.setVisible(true);
        objventa_clientes.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ver_productos_cActionPerformed

    private void btn_ver_carrito_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_carrito_cActionPerformed
        this.dispose();
        carrito_clientes objproductos_agregados= new carrito_clientes();
        objproductos_agregados.setVisible(true);
        objproductos_agregados.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ver_carrito_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar_sesion_cliente;
    private javax.swing.JButton btn_ver_carrito_c;
    private javax.swing.JButton btn_ver_productos_c;
    // End of variables declaration//GEN-END:variables
}
